@echo off
:: HealthyPartner v2 — One-Click Installer (Windows)
:: Run once: double-click this file or run from Command Prompt
setlocal EnableDelayedExpansion

:: ── Resolve project root ──────────────────────────────────────────────────────
set "INSTALLER_DIR=%~dp0"
set "PROJECT_ROOT=%INSTALLER_DIR%.."
cd /d "%PROJECT_ROOT%"

echo.
echo ============================================
echo   HealthyPartner v2 -- Installer
echo   Privacy-first local healthcare AI
echo ============================================
echo.

:: ── Step 1: Python 3.10+ ─────────────────────────────────────────────────────
echo [1/7] Checking Python...

set "PYTHON_CMD="
for %%p in (python3 python py) do (
    if not defined PYTHON_CMD (
        %%p --version >nul 2>&1 && (
            for /f "tokens=2" %%v in ('%%p --version 2^>^&1') do (
                set "PY_VER=%%v"
            )
            set "PYTHON_CMD=%%p"
        )
    )
)

if not defined PYTHON_CMD (
    echo [ERROR] Python not found.
    echo.
    echo   Download Python 3.11 from: https://www.python.org/downloads/
    echo   Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

echo [OK]   Python found: %PYTHON_CMD% %PY_VER%

:: ── Step 2: Ollama ────────────────────────────────────────────────────────────
echo.
echo [2/7] Checking Ollama...

where ollama >nul 2>&1
if errorlevel 1 (
    echo [WARN] Ollama is not installed.
    echo.
    echo   Download and install from: https://ollama.com/download
    echo   Run the .exe installer, then come back and press any key.
    echo.
    pause

    where ollama >nul 2>&1
    if errorlevel 1 (
        echo [ERROR] Ollama still not found. Install it and re-run setup.bat.
        pause
        exit /b 1
    )
)

echo [OK]   Ollama found

:: ── Step 3: Virtual environment ───────────────────────────────────────────────
echo.
echo [3/7] Setting up virtual environment...

if exist ".venv\" (
    echo [INFO]  Virtual environment already exists -- skipping
) else (
    %PYTHON_CMD% -m venv .venv
    echo [OK]   Virtual environment created
)

call .venv\Scripts\activate.bat

:: ── Step 4: Python dependencies ───────────────────────────────────────────────
echo.
echo [4/7] Installing Python dependencies (this may take 2-5 minutes)...

python -m pip install --upgrade pip --quiet
pip install -r requirements.txt --quiet
echo [OK]   Python dependencies installed

:: ── Step 5: Pull Ollama models ────────────────────────────────────────────────
echo.
echo [5/7] Pulling AI models via Ollama...
echo.
echo   This downloads approximately 3 GB. Only needed once.
echo   Please keep this window open and wait.
echo.

:: Detect RAM (approximate via WMIC)
set "TOTAL_RAM_GB=8"
for /f "skip=1 tokens=*" %%m in ('wmic computersystem get TotalPhysicalMemory ^| findstr /r "[0-9]"') do (
    set "RAM_BYTES=%%m"
)
:: Convert bytes to GB (rough division)
if defined RAM_BYTES (
    set /a TOTAL_RAM_GB=!RAM_BYTES:~0,-9! + 0
    if !TOTAL_RAM_GB! LSS 1 set "TOTAL_RAM_GB=8"
)

set "MAIN_MODEL=qwen3:4b"
set "FAST_MODEL=qwen2.5:0.5b"
set "TIER=balanced"

if !TOTAL_RAM_GB! GEQ 16 (
    set "TIER=quality (16 GB+ RAM)"
) else if !TOTAL_RAM_GB! GEQ 8 (
    set "TIER=balanced (8 GB+ RAM)"
) else (
    set "MAIN_MODEL=qwen2.5:1.5b"
    set "TIER=ultra-light (4 GB RAM)"
)

echo   Detected ~%TOTAL_RAM_GB% GB RAM -- using %TIER% tier
echo   Main model : %MAIN_MODEL%
echo   Fast model : %FAST_MODEL%
echo.

:: Start Ollama service
echo Starting Ollama service...
start /b ollama serve
timeout /t 3 /nobreak >nul

echo Pulling %MAIN_MODEL% ...
ollama pull %MAIN_MODEL%
echo [OK]   %MAIN_MODEL% ready

echo Pulling %FAST_MODEL% ...
ollama pull %FAST_MODEL%
echo [OK]   %FAST_MODEL% ready

:: ── Step 6: Create data directories ──────────────────────────────────────────
echo.
echo [6/7] Creating data directories...
if not exist "data\"           mkdir data
if not exist "db\"             mkdir db
if not exist "downloaded_files\" mkdir downloaded_files
echo [OK]   Directories ready

:: ── Step 7: Write .env and start.bat ─────────────────────────────────────────
echo.
echo [7/7] Creating configuration and launch script...

if not exist ".env" (
    (
        echo # HealthyPartner v2 -- Auto-generated by installer
        echo HP_MODEL_TIER=balanced
        echo HP_MAIN_MODEL=%MAIN_MODEL%
        echo HP_FAST_MODEL=%FAST_MODEL%
    ) > .env
    echo [OK]   .env written
) else (
    echo [INFO]  .env already exists -- skipping
)

:: Write start.bat
(
echo @echo off
echo :: HealthyPartner v2 -- Launch Script
echo :: Double-click this file to start HealthyPartner
echo setlocal
echo cd /d "%%~dp0"
echo.
echo echo.
echo echo Starting HealthyPartner v2...
echo echo.
echo.
echo :: Start Ollama
echo echo [1/3] Starting Ollama...
echo start /b ollama serve
echo timeout /t 3 /nobreak ^>nul
echo.
echo :: Activate venv and start backend
echo call .venv\Scripts\activate.bat
echo echo [2/3] Starting backend on http://localhost:8000 ...
echo start /b uvicorn app.main:app --host 0.0.0.0 --port 8000
echo timeout /t 4 /nobreak ^>nul
echo.
echo :: Start frontend
echo echo [3/3] Starting frontend...
echo echo.
echo echo HealthyPartner is running!
echo echo Open your browser at: http://localhost:8501
echo echo Close this window to stop.
echo echo.
echo streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
) > start.bat

echo [OK]   start.bat created

:: ── Done ─────────────────────────────────────────────────────────────────────
echo.
echo ============================================
echo   Installation Complete!
echo ============================================
echo.
echo   To start HealthyPartner:
echo   Double-click  start.bat
echo   or run it from Command Prompt.
echo.
pause
